config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: redirect('/cocktails')
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/dose.rb
# frozen_string_literal: true

class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true

  # TODO: Dose is uniqe for a given cocktail/ingredient couple
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail.id)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">

  <h1 class="text-white cocktail-title fadein">Mister Cocktail</h1>
  <div class="create-new-div">
    <%= link_to 'Create new drink', new_cocktail_path, class: "btn btn-light new-drink-btn fadein" %>
  </div>
  <div class="row cocktails fadein">
    <% @cocktails.each do |cocktail| %>
    <div class="col-sm-12 col-md-6 col-lg-4 w-100">

      <div class="d-flex justify-content-center">
        <div class="cocktail rounded shadow">
          <h4 class="text-center m-2"><%= cocktail.name %></h4>
          <hr class="w-100">


          <% unless cocktail.ingredients.empty? %>
          <h6 class="ml-2 mt-1">Ingredients:</h6>
          <% end %>
          <ul class="overflow-auto">
            <% cocktail.ingredients.each do |ingredient|%>
            <li><%= ingredient.name %></li>
            <% end %>
          </ul>
          <%= link_to "View", cocktail_path(cocktail.id), class: "view-link" %>

        </div>

      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
    <h1 class="text-white fadein cocktail-title">New Cocktail</h1>

    <div class="show-cocktail shadow rounded fadein p-5">
        <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit , class: "btn btn-success"%>
        <% end %>

    </div>
</div>

app/views/cocktails/show.html.erb
<%# put stuff here %>
<div class="container">
    <h1 class="text-white cocktail-title fadein"><%= @cocktail.name %></h1>
    <div class="show-cocktail shadow rounded fadein">
        <div class="row ">
            <div class="col-sm-12 col-lg-4">
                <%= cl_image_tag @cocktail.photo.key, width: 300, height: 300, crop: :fill %>

            </div>

            <div class="col-sm-12 col-lg-4">
                <% if @cocktail.doses.empty? %>
                <h3>Add some Ingredients -></h3>
                <% else %>
                <h3>Instructions:</h3>
                <% @cocktail.doses.each do |dose| %>
                <p><%= dose.ingredient.name %>:
                    <%= dose.description %><%= link_to  cocktail_dose_path(@cocktail.id, dose), method: "delete", class: "text-decoration-none" do %>
                    <i class="fa fa-trash delete-icon"></i>

                    <% end %></p>

                <% end %>
                <% end %>

            </div>

            <div class="col-sm-12 col-lg-4">
                <%= simple_form_for([@cocktail, @dose]) do |f| %>
                <%= f.association :ingredient %>
                <%= f.input :description %>
                <%= f.submit "Submit", class: "btn btn-success" %>
                <% end %>

            </div>


        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="waveWrapper waveAnimation">
    <div class="waveWrapperInner bgTop">
      <% unless request.env['PATH_INFO'] == "/cocktails" %>
      <%= link_to cocktails_path do %>
      <h3 class="text-white position-absolute m-4 fadein">Mister Cocktail</h3>
      <% end %>
      <% end %>
      <%= yield %>
      <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')">
      </div>
    </div>
    <div class="waveWrapperInner bgMiddle">
      <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')">

      </div>
    </div>
    <div class="waveWrapperInner bgBottom">
      <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')">
      </div>
    </div>
  </div>
</body>

</html>